server:
  port: 8000
  servlet:
    context-path: /api/

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: admin
    driverClassName: com.mysql.cj.jdbc.Driver
  liquibase:
    change-log: classpath:/db/liquibase-changelog.xml

custom:
  filter.host: localhost:8200
